### ISSUE TITLE
[Bug]: Docker: "Unsupported Provider: ", potentially env vars not loaded

### ISSUE THREAD

**Issue by yihuanlin** [u14app/deep-research#73]
### Bug Description

It appears that `useSettingStore.getState()` is not returning the provider set in environment.

### Steps to Reproduce

docker-compose.yml using .env file:
```
services:
  deep-research:
    image: xiangfa/deep-research
    container_name: deep-research
    env_file:
      - .env
    ports:
      - 3333:3000
```
or docker-compose.yml:
```
services:
  deep-research:
    image: xiangfa/deep-research
    container_name: deep-research
    environment:
      - ACCESS_PASSWORD=***
      - GOOGLE_GENERATIVE_AI_API_KEY=AIzaSy***
      - MCP_TASK_MODEL=gemini-2.5-flash-preview-05-20
      - MCP_THINKING_MODEL=gemini-2.5-flash-preview-05-20
      - MCP_AI_PROVIDER=google
    ports:
      - 3333:3000
```

### Expected Behavior

MCP calling `deep-research` or `write-research-plan`
```
{
  "params": {
    "query": "Notch2 cleavage alternative S3 site, mutation in gamma secretase, subunit/domain/motif in gamma secretase for site recognition, canonical GV site absence, alternative VL site, unstable NICD"
  },
  "response": {
    "content": [
      {
        "type": "text",
        "text": "Error: Unsupported Provider: "
      }
    ],
    "isError": true
  }
}
```

### Deployment Method

- [x] Docker
- [ ] Vercel
- [ ] Server
