### ISSUE TITLE
[Bug]: 500 Internal Error and SyntaxError: Unexpected end of JSON input when using Server-Side Proxy (Searxng/Uni-API) in Docker Compose

### ISSUE THREAD

**Issue by gaoyuyun** [u14app/deep-research#91]
### Bug Description

I'm encountering two related issues when using deep-research as a server-side proxy for searxng and uni-api within a Docker Compose environment.

1. **Issue with searxng proxy**: When deep-research (xiangfa/deep-research) attempts to proxy search requests to searxng (searxng/searxng), it receives a 500 Internal Server Error and logs a SyntaxError: Unexpected end of JSON input. This indicates that deep-research is not receiving a complete or valid JSON response from searxng when acting as a proxy, despite searxng being accessible internally and externally.
2. **Issue with uni-api (remote deployment)**: When uni-api (yym68686/uni-api) is deployed on a remote server (instead of locally in Docker Compose), deep-research fails to load models from it. The browser console shows a {"code":500,"message":"fetch failed"} error, suggesting a network connectivity or proxying problem when deep-research tries to reach an external uni-api endpoint. uni-api itself functions correctly when called directly from other clients (e.g., Cherry Studio).

### Environment Setup:

- Docker and Docker Compose installed.
- Modified searxng's settings.yaml with `search.formats: ["json", "html"]`
- The following docker-compose.yml is used:

```
version: '3.8'

services:
  searxng:
    container_name: searxng
    image: searxng/searxng:latest
    restart: unless-stopped
    networks:
      - my_shared_network
    # ports:
    #   - "127.0.0.1:8080:8080" # Ports commented out, using internal Docker networking
    volumes:
      - ./searxng:/etc/searxng:rw
    environment:
      - SEARXNG_BASE_URL=https://${SEARXNG_HOSTNAME:-localhost}/
      - UWSGI_WORKERS=${SEARXNG_UWSGI_WORKERS:-4}
      - UWSGI_THREADS=${SEARXNG_UWSGI_THREADS:-4}

  uni-api:
    image: yym68686/uni-api:latest
    container_name: uni-api
    restart: unless-stopped
    # ports:
    #   - 8000:8000 # Ports commented out, using internal Docker networking
    networks:
      - my_shared_network
    environment:
      - CONFIG_URL=${UNIAPI_CONFIG_URL}

  deep-research:
    image: xiangfa/deep-research
    container_name: deep-research
    environment:
      - ACCESS_PASSWORD=${DEEP_RESEARCH_PASSWORD} # Replace with your password
      - OPENAI_COMPATIBLE_API_BASE_URL=http://uni-api:8000 # Points to internal uni-api initially
      - OPENAI_COMPATIBLE_API_KEY=${DEEP_RESEARCH_API_KEY} # Replace with your API key
      - SEARXNG_API_BASE_URL=http://searxng:8080 # Points to internal searxng
    ports:
        - 3333:3000 # External port for deep-research
    networks:
      - my_shared_network

networks:
  my_shared_network:
    driver: bridge
```

### Steps to Reproduce (Scenario 1 - searxng issue):

1. Save the docker-compose.yml file.
2. Run docker-compose up -d to start all services.
3. Access deep-research and use server-side proxy mode.
4. Within the deep-research UI, attempt to perform a search query (which internally uses searxng via deep-research's proxy).
5. The browser shows the 500 Internal Server Error and SyntaxError: Unexpected end of JSON input.

### Steps to Reproduce (Scenario 2 - uni-api remote issue):

1. Deploy uni-api (yym68686/uni-api) on a separate, remote server, ensuring it's publicly accessible.
2. Update the docker-compose.yml for deep-research to point to the remote uni-api:
```
# ...
deep-research:
  # ...
  environment:
    # ...
    - OPENAI_COMPATIBLE_API_BASE_URL=http://<REMOTE_UNI_API_IP_OR_HOSTNAME>:8000 # Replace with your remote uni-api address
    # ...
```
3. Restart deep-research (docker-compose restart deep-research).
4. Access deep-research and attempt to load models within deep-research, the browser's developer console for network errors show {"code":500,"message":"fetch failed"}.

### Expected Behavior

1. deep-research should successfully proxy search requests to searxng and receive a valid JSON response, allowing search results to be displayed.
2. deep-research should successfully connect to and load models from uni-api, regardless of whether uni-api is deployed locally within the same Docker network or on a remote server.

### Deployment Method

- [x] Docker
- [ ] Vercel
- [ ] Server

### Desktop OS

Windows11

### Desktop Browser

Edge

### Desktop Browser Version

137.0.3296.68

### 1. deep-research console output when proxying to searxng (Scenario 1):
```
✓ Starting...
✓ Ready in 82ms
{
  cookies: RequestCookies {},
    nextUrl: {
  href: 'http://443bc8495b3f:3000/api/search/searxng/search?q=xxx&categories=general%2Cimages&engines=google%2Cbing%2Cduckduckgo%2Cbrave%2Cwikipedia%2Cbing_images%2Cgoogle_images&lang=auto&format=json&autocomplete=google',
  origin: 'http://443bc8495b3f:3000',
  protocol: 'http:',
  username: '',
  password: '',
  host: '443bc8495b3f:3000',
  hostname: '443bc8495b3f',
  port: '3000',
  pathname: '/api/search/searxng/search',
  search: '?q=xxx&categories=general%2Cimages&engines=google%2Cbing%2Cduckduckgo%2Cbrave%2Cwikipedia%2Cbing_images%2Cgoogle_images&lang=auto&format=json&autocomplete=google',
  searchParams: URLSearchParams {
  [Symbol(query)]: [
  'q',
  'xxx',
  'categories',
  'general,images',
    'engines',
  'google,bing,duckduckgo,brave,wikipedia,bing_images,google_images',
 
,
 
,
  'format',
 
,
  'autocomplete',
  'google'
],
  [Symbol(context)]: URL {
  [Symbol(context)]: URLContext {
  href: 'http://443bc8495b3f:3000/api/search/searxng/search?q=xxx&categories=general%2Cimages&engines=google%2Cbing%2Cduckduckgo%2Cbrave%2Cwikipedia%2Cbing_images%2Cgoogle_images&lang=auto&format=json&autocomplete=google',
  protocol_end: 5,
  username_end: 7,
  host_start: 7,
  host_end: 19,
  pathname_start: 24,
  search_start: 50,
  hash_start: 4294967295,
  port: 3000,
  scheme_type: 0
}
}
},
  hash: ''
},
  url: 'http://443bc8495b3f:3000/api/search/searxng/search?q=xxx&categories=general%2Cimages&engines=google%2Cbing%2Cduckduckgo%2Cbrave%2Cwikipedia%2Cbing_images%2Cgoogle_images&lang=auto&format=json&autocomplete=google',
  bodyUsed: false,
  cache: 'default',
  credentials: 'same-origin',
  destination: '',
    headers: {
  accept: '*/*',
  accept-encoding: 'gzip, deflate',
  accept-language: 'zh-CN,zh;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6',
  authorization: 'Bearer 819b417a2d839c4aa048f86a1b738702',
  connection: 'keep-alive',
  content-length: '0',
  content-type: 'application/json',
  dnt: '1',
  host: '192.168.2.20:3333',
  origin: 'http://192.168.2.20:3333',
  referer: 'http://192.168.2.20:3333/',
  user-agent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/137.0.0.0 Safari/537.36 Edg/137.0.0.0',
  x-forwarded-for: '172.20.0.1',
  x-forwarded-host: '192.168.2.20:3333',
  x-forwarded-port: '3000',
  x-forwarded-proto: 'http'
},
  integrity: '',
  keepalive: false,
  method: 'POST',
  mode: 'cors',
  redirect: 'follow',
  referrer: 'about:client',
  referrerPolicy: '',
  signal: AbortSignal {
  [Symbol(kEvents)]: SafeMap(0) {},
  [Symbol(events.maxEventTargetListeners)]: 10,
  [Symbol(events.maxEventTargetListenersWarned)]: false,
  [Symbol(kAborted)]: false,
  [Symbol(kReason)]: undefined,
  [Symbol(kComposite)]: false
}
}
⨯ SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at async x (.next/server/app/api/search/searxng/[...slug]/route.js:1:1316)
    at async eg.do (.next/server/edge-chunks/19.js:16:11537)
    at async eg.handle (.next/server/edge-chunks/19.js:16:13822)
    at async e_.handler (.next/server/edge-chunks/19.js:17:31215)
⨯ SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at async x (.next/server/app/api/search/searxng/[...slug]/route.js:1:1316)
    at async eg.do (.next/server/edge-chunks/19.js:16:11537)
    at async eg.handle (.next/server/edge-chunks/19.js:16:13822)
    at async e_.handler (.next/server/edge-chunks/19.js:17:31215)
```
### 2. Browser console error when connecting to remote uni-api (Scenario 2):
```
{"code":500,"message":"fetch failed"}
```

**Comment by Amery2010** [comment]
SearXNG enables the json format API by setting the following parameters in the `searxng/settings.yml` file:

```yml
search:
  formats:
    - html
    - json
```
